employeesNumber=int(input())
employeesWorkingHour=int(input())
priceForPerHour=float(input())
print("NUMBER =",employeesNumber)
print("SALARY = U$ {:.2f}".format(employeesWorkingHour*priceForPerHour))